language: node_js
node_js:
  - 12.13.0
dist: bionic
cache:
  directories:
    - "$HOME/.cache"
before_install:
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
  - sudo apt-get update
  - sudo apt-get install python3 python
  - sudo apt-get install python3-setuptools
  - sudo apt-get install docker.io docker-compose
  # - sudo rm /usr/local/bin/docker-compose
  # - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  # - chmod +x docker-compose
  # - sudo mv docker-compose /usr/local/bin
  - git clone https://github.com/EyeSeeTea/d2-docker.git
  - cd d2-docker/
  - git checkout origin/test
  - sudo python3 setup.py install
  - d2-docker --help
  - sudo apt-get remove golang-docker-credential-helpers
  - sudo systemctl unmask docker.service
  - sudo systemctl unmask docker.socket
  - sudo systemctl start docker.service
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker pull eyeseetea/dhis2-data:2.30-datasync-sender
  - d2-docker start eyeseetea/dhis2-data:2.30-datasync-sender -d
install:
  - yarn install --frozen-lockfile
  - yarn cy:verify
  - yarn build
script:
  - PORT=8081 REACT_APP_DHIS2_BASE_URL=http://localhost:8080 REACT_APP_CYPRESS=true yarn start &
  - yarn wait-on http-get://localhost:8080
  - yarn wait-on http-get://localhost:8081
  - CYPRESS_EXTERNAL_API=http://localhost:8080 CYPRESS_ROOT_URL=http://localhost:8081 yarn cy:e2e:run
  - kill $(jobs -p) || true
addons:
  apt:
    packages:
    - libgconf-2-4
# services:
#   - docker
# python:
#   - "3.6"

