language: node_js
node_js:
  - 12.13.0
cache:
  directories:
    - "$HOME/.cache"
before_install:
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-setuptools
  - git clone https://github.com/EyeSeeTea/d2-docker.git
  - cd d2-docker/
  - sudo python3 setup.py install
  - sudo d2-docker --help
  - sudo docker login
  - sudo d2-docker start eyeseetea/dhis2-data:2.30-datasync-sender
install:
  - yarn install --frozen-lockfile
  - yarn cy:verify
  - yarn build
script:
  - PORT=8081 REACT_APP_DHIS2_BASE_URL=http://localhost:8080 REACT_APP_CYPRESS=true yarn start &
  - yarn wait-on http-get://localhost:8081
  - CYPRESS_EXTERNAL_API=http://localhost:8080 CYPRESS_ROOT_URL=http://localhost:8081 yarn cy:e2e:run --key $CYPRESS_KEY
  - kill $(jobs -p) || true
addons:
  apt:
    packages:
    - libgconf-2-4
services:
  - docker
python:
  - "3.6"

